# -*- coding: utf-8 -*-
"""AI_Solar_Sales_Assistant.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuH8IHxPfG3P3Uys8lZdca9vnPq9mR-T
"""

!pip install streamlit groq reportlab pandas plotly pyngrok -q

import os

PROJECT_NAME = "AI_Solar_Sales_Assistant"

folders = [
    PROJECT_NAME,
    f"{PROJECT_NAME}/utils",
    f"{PROJECT_NAME}/reports",
    f"{PROJECT_NAME}/assets"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("✅ Project structure created successfully!")

calculator_code = '''
import math

class SolarCalculator:

    def __init__(self):

        self.cost_per_kw = 70000
        self.panel_power = 550
        self.unit_rate = 12

    def get_system_size(self, bill):

        if bill <= 1100:
            return 1
        elif bill <= 2200:
            return 2
        elif bill <= 3300:
            return 3
        elif bill <= 4400:
            return 4
        elif bill <= 5500:
            return 5
        elif bill <= 6600:
            return 6
        elif bill <= 7700:
            return 7
        elif bill <= 8800:
            return 8
        elif bill <= 9900:
            return 9
        else:
            return 10

    def calculate(self, bill, roof):

        system_kw = self.get_system_size(bill)

        panels = math.ceil((system_kw * 1000) / self.panel_power)

        roof_required = panels * 30

        installation_cost = system_kw * self.cost_per_kw

        if system_kw == 1:
            subsidy = 30000
        elif system_kw == 2:
            subsidy = 60000
        else:
            subsidy = 78000

        final_cost = installation_cost - subsidy

        monthly_generation = system_kw * 120

        monthly_savings = monthly_generation * self.unit_rate

        yearly_savings = monthly_savings * 12

        payback = round(final_cost / yearly_savings, 1)

        return {
            "system_kw": system_kw,
            "panels": panels,
            "roof_required": roof_required,
            "installation_cost": installation_cost,
            "subsidy": subsidy,
            "final_cost": final_cost,
            "monthly_generation": monthly_generation,
            "monthly_savings": monthly_savings,
            "yearly_savings": yearly_savings,
            "payback": payback
        }
'''

with open("AI_Solar_Sales_Assistant/utils/calculator.py", "w") as f:
    f.write(calculator_code)

print("✅ calculator.py created successfully!")

pdf_code = '''
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

def generate_pdf(customer, mobile, city, result):

    file_name = "reports/Solar_Proposal.pdf"

    doc = SimpleDocTemplate(file_name)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>AI Solar Sales Assistant</b>", styles["Title"]))
    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Customer Name:</b> {customer}", styles["Normal"]))
    story.append(Paragraph(f"<b>Mobile:</b> {mobile}", styles["Normal"]))
    story.append(Paragraph(f"<b>City:</b> {city}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Recommended System:</b> {result['system_kw']} kW", styles["Normal"]))
    story.append(Paragraph(f"<b>Panels Required:</b> {result['panels']}", styles["Normal"]))
    story.append(Paragraph(f"<b>Installation Cost:</b> ₹{result['installation_cost']:,}", styles["Normal"]))
    story.append(Paragraph(f"<b>Government Subsidy:</b> ₹{result['subsidy']:,}", styles["Normal"]))
    story.append(Paragraph(f"<b>Final Cost:</b> ₹{result['final_cost']:,}", styles["Normal"]))
    story.append(Paragraph(f"<b>Monthly Savings:</b> ₹{result['monthly_savings']:,}", styles["Normal"]))
    story.append(Paragraph(f"<b>Yearly Savings:</b> ₹{result['yearly_savings']:,}", styles["Normal"]))
    story.append(Paragraph(f"<b>Payback Period:</b> {result['payback']} Years", styles["Normal"]))

    doc.build(story)

    return file_name
'''

with open("AI_Solar_Sales_Assistant/utils/pdf_generator.py", "w") as f:
    f.write(pdf_code)

print("✅ pdf_generator.py created successfully!")

app_code = '''
import streamlit as st
from utils.calculator import SolarCalculator
from utils.pdf_generator import generate_pdf
import pandas as pd
import plotly.express as px

st.set_page_config(
    page_title="AI Solar Sales Assistant",
    page_icon="☀️",
    layout="wide"
)

calculator = SolarCalculator()

st.sidebar.title("☀️ AI Solar Sales Assistant")

page = st.sidebar.radio(
    "Navigation",
    [
        "🏠 Home",
        "☀️ Solar Calculator",
        "📊 Dashboard",
        "ℹ️ About"
    ]
)

# ---------------- HOME ----------------

if page == "🏠 Home":

    st.title("☀️ AI Solar Sales Assistant")

    st.subheader(
        "Calculate solar system recommendations, subsidy, savings and payback period."
    )

    st.markdown("---")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Customers", "1250")
    c2.metric("Projects", "680")
    c3.metric("Accuracy", "96%")
    c4.metric("ROI", "4.8 Years")

    st.markdown("---")

    st.header("Features")

    st.success("☀️ Solar Recommendation")
    st.success("💰 Cost Estimation")
    st.success("🎁 Government Subsidy")
    st.success("📈 Savings Calculator")
    st.success("📄 PDF Proposal")
    st.success("📊 Dashboard")

# ---------------- SOLAR CALCULATOR ----------------

elif page == "☀️ Solar Calculator":

    st.title("☀️ Solar Calculator")

    customer = st.text_input("Customer Name")

    mobile = st.text_input("Mobile Number")

    city = st.text_input("City")

    property_type = st.selectbox(
        "Property Type",
        ["Residential", "Commercial"]
    )

    phase = st.selectbox(
        "Connection Type",
        ["Single Phase", "Three Phase"]
    )

    bill = st.number_input(
        "Monthly Electricity Bill (₹)",
        min_value=0,
        value=1500,
        step=100
    )

    roof = st.number_input(
        "Roof Area (sq.ft)",
        min_value=100,
        value=600,
        step=10
    )

    if st.button("Calculate Recommendation"):

        result = calculator.calculate(bill, roof)

        st.session_state["result"] = result
        st.session_state["customer"] = customer
        st.session_state["mobile"] = mobile
        st.session_state["city"] = city

        st.success("Recommendation Generated Successfully")

        c1, c2, c3 = st.columns(3)

        c1.metric("System Size", str(result["system_kw"]) + " kW")
        c2.metric("Panels", result["panels"])
        c3.metric("Payback", str(result["payback"]) + " Years")

        st.markdown("---")

        st.write(f"Installation Cost : ₹{result['installation_cost']:,}")
        st.write(f"Government Subsidy : ₹{result['subsidy']:,}")
        st.write(f"Final Cost : ₹{result['final_cost']:,}")
        st.write(f"Monthly Generation : {result['monthly_generation']} Units")
        st.write(f"Monthly Savings : ₹{result['monthly_savings']:,}")
        st.write(f"Yearly Savings : ₹{result['yearly_savings']:,}")
        pdf_path = generate_pdf(customer, mobile, city, result)

        with open(pdf_path, "rb") as file:
            st.download_button(
                label="📄 Download Proposal PDF",
                data=file,
                file_name="Solar_Proposal.pdf",
                mime="application/pdf"
            )

        if roof >= result["roof_required"]:
            st.success("✅ Roof Area is Sufficient")
        else:
            st.error(f"❌ Minimum Roof Required : {result['roof_required']} sq.ft")

# ---------------- DASHBOARD ----------------

elif page == "📊 Dashboard":

    st.title("📊 Solar Dashboard")

    if "result" not in st.session_state:
        st.warning("⚠️ Please calculate a recommendation first.")

    else:

        result = st.session_state["result"]

        col1, col2, col3 = st.columns(3)

        col1.metric("System Size", f"{result['system_kw']} kW")
        col2.metric("Panels", result["panels"])
        col3.metric("Payback", f"{result['payback']} Years")

        cost = pd.DataFrame({
            "Category": [
                "Installation Cost",
                "Government Subsidy",
                "Final Cost"
            ],
            "Amount": [
                result["installation_cost"],
                result["subsidy"],
                result["final_cost"]
            ]
        })

        fig = px.bar(
            cost,
            x="Category",
            y="Amount",
            text="Amount",
            title="Cost Analysis"
        )

        st.plotly_chart(fig, use_container_width=True)

        savings = pd.DataFrame({
            "Type": [
                "Monthly Savings",
                "Yearly Savings"
            ],
            "Amount": [
                result["monthly_savings"],
                result["yearly_savings"]
            ]
        })

        fig2 = px.pie(
            savings,
            names="Type",
            values="Amount",
            title="Savings Distribution"
        )

        st.plotly_chart(fig2, use_container_width=True)

# ---------------- ABOUT ----------------

else:

    st.title("About")

    st.write("Project : AI Solar Sales Assistant")

    st.write("Developer : Padmaja Amberkar")

    st.write("Built using Python, Streamlit, Plotly and ReportLab")

'''

with open("AI_Solar_Sales_Assistant/app.py", "w") as f:
    f.write(app_code)

print("✅ app.py created successfully!")

requirements = """
streamlit
groq
reportlab
pandas
plotly
"""

with open("AI_Solar_Sales_Assistant/requirements.txt", "w") as f:
    f.write(requirements.strip())

print("✅ requirements.txt created successfully!")

readme = """
# ☀️ AI Solar Sales Assistant

An AI-powered Solar Sales Assistant built using Python and Streamlit.

## Features

- Solar System Recommendation
- Government Subsidy Calculator
- Installation Cost Estimation
- Monthly & Yearly Savings
- Roof Area Validation
- PDF Proposal Generator
- Dashboard with Charts

## Technologies Used

- Python
- Streamlit
- Plotly
- ReportLab
- Groq AI
"""

with open("AI_Solar_Sales_Assistant/README.md", "w") as f:
    f.write(readme)

print("✅ README.md created successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %cd AI_Solar_Sales_Assistant
!streamlit run app.py